export enum NotificationType {
  JOB_CREATED = 'JOB_CREATED',
  WORKER_ACCEPTED = 'WORKER_ACCEPTED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  JOB_CANCELLED = 'JOB_CANCELLED',
  NEW_RESPONSE = 'NEW_RESPONSE',
}
